M48
; DRILL file {KiCad 9.0.0} date 2025-02-26T14:35:56+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-26T14:35:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X123.169Y-110.94
X124.185Y-105.86
X125.201Y-110.94
M30
